version: '3.9'

networks:
  local:

services:

  potgres:
    container_name: "potgres"
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=quarkus_test 
      - POSTGRES_PASSWORD=quarkus_test 
      - POSTGRES_DB=quarkus_test
    networks:
      - local
